export const styles = {
    container: {
        padding: '20px',
        maxWidth: '1200px',
        margin: '0 auto',
        textAlign: 'center' as const,
    },
    title: {
        fontSize: '24px',
        marginBottom: '10px',
    },
    logoutButton: {
        padding: '10px 20px',
        fontSize: '16px',
        backgroundColor: '#007bff',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        position: 'absolute' as const,
        top: '20px',
        right: '20px',
    },
    subtitle: {
        fontSize: '20px',
        margin: '20px 0',
    },
    eventCard: {
        backgroundColor: '#fff',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    eventTable: {
        width: '100%',
        borderCollapse: 'collapse' as const,
    },
    tableHeader: {
        padding: '10px',
        backgroundColor: '#f5f5f5',
        color: '#333',
        textAlign: 'left' as const,
        fontWeight: 'bold',
    },
    tableRow: {
        borderBottom: '1px solid #ddd',
        height: '60px',
    },
    tableCell: {
        padding: '10px',
        textAlign: 'left' as const,
        verticalAlign: 'middle',
    },
    countryFlag: {
        display: 'inline-block',
        marginRight: '10px',
        verticalAlign: 'middle',
    },
    eventDetails: {
        display: 'inline-block',
        verticalAlign: 'middle',
    },
    icon: {
        marginRight: '8px',
        fontSize: '18px', 
        verticalAlign: 'middle',
    },
    formTitle: {
        fontSize: '18px',
        marginBottom: '10px',
    },
    dateContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        marginBottom: '10px',
    },
    dateInputWrapper: {
        flex: '1',
        marginRight: '10px',
    },
    label: {
        display: 'block',
        marginBottom: '5px',
        fontSize: '14px',
        color: '#555',
    },
    input: {
        width: '100%',
        padding: '10px',
        marginBottom: '10px',
        fontSize: '16px',
        borderRadius: '4px',
        border: '1px solid #ddd',
    },
    addButton: {
        width: '100%',
        padding: '10px',
        fontSize: '16px',
        backgroundColor: '#007bff',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        marginTop: '20px',
    },
    error: {
        color: 'red',
        marginBottom: '10px',
        fontSize: '14px',
        textAlign: 'center' as const,
    },
    actionButton: {
        padding: '5px 10px',
        fontSize: '14px',
        backgroundColor: '#007bff',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        marginRight: '5px',
    },
    deleteButton: {
        padding: '5px 10px',
        fontSize: '14px',
        backgroundColor: '#dc3545',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
};

export const customModalStyles = {
    content: {
        top: '50%',
        left: '50%',
        right: 'auto',
        bottom: 'auto',
        marginRight: '-50%',
        transform: 'translate(-50%, -50%)',
        padding: '20px',
        borderRadius: '8px',
        maxWidth: '500px',
        width: '100%',
    },
};
